import './globals.css'

import type { Metadata } from 'next'
import { Geist, Inter } from 'next/font/google'
import { AppWrapper } from '@/contexts/state'

import Header from '@/components/Header/Header'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700'], 
})

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700'], 
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <AppWrapper>
      <html lang='en'>
        <body
          className={`${geistSans.variable} ${inter.variable} antialiased`}
        >
          <Header />
          <main>{children}</main>
        </body>
      </html>
    </AppWrapper>
  )
}
